export const CartActionTypes = {
  TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  INC_ITEM_QUANTITY: 'INC_ITEM_QUANTITY',
  DEC_ITEM_QUANTITY: 'DEC_ITEM_QUANTITY',
  CLEAR_CART: 'CLEAR_CART'
};
